[tool.poetry]
name = "cato"
version = "0.34.0"
description = "coolest project"
authors = ["Jan Honsbrok <jan.honsbrok@gmail.com>"]
include = [
    "cato_server/static/**/*",
    "cato_api_models/**/*"
]
packages = [
    { include = "cato" },
    { include = "cato_server" },
    { include = "cato_api_client" },
    { include = "cato_api_models" },
]

[tool.poetry.scripts]
cato = 'cato.__main__:main'
cato_server_admin = 'cato_server.cato_server_admin:main'
db_load_generator = 'cato_server.db_load_generator:main'

[tool.poetry.dependencies]
python = "^3.7"
emoji = "^1.2.0"
pinject = "^0.14.1"
jsonschema = "^3.2.0"
contexttimer = "^0.3.3"
humanfriendly = "^9.1"
tabulate = "^0.8.9"
Jinja2 = "^2.11.2"
attrs = "^20.3.0"
alembic = "^1.4.3"
SQLAlchemy = "^1.3.20"
py-cpuinfo = "^7.0.0"
psutil = "^5.7.3"
Flask = "^1.1.2"
gevent = "^21.1.2"
marshmallow = "^3.9.1"
requests = "^2.25.0"
marshmallow-enum = "^1.5.1"
python-dateutil = "^2.8.1"
pathvalidate = "^2.3.1"
pika = "^1.2.0"
future = "^0.18.2"
Flask-Twisted = "^0.1.2"
schedule = "^1.0.0"
psycopg2-binary = "^2.8.6"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
pytest = "^6.1.2"
mypy = "^0.812"
bumpversion = "^0.6.0"
coverage = "^5.3"
flake8 = "^3.8.4"
flake8-print = "^4.0.0"
GitPython = "^3.1.11"
snapshottest = "^0.6.0"
selenium = "^3.141.0"
chromedriver-py = "87.0.4280.88"
Pillow = "^8.1.0"
Faker = "^6.5.2"
pytest-postgresql = "^2.6.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
