[tool.poetry]
name = "cato"
version = "0.1.0"
description = ""
authors = ["Jan <jan.honsbrok@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
emoji = "^0.6.0"
pinject = "^0.14.1"
jsonschema = "^3.2.0"
oiio = [
    { path = "oiio_packages/oiio-2.0.5-cp37-none-win_amd64.whl", markers = "sys_platform == win32" },
    { path = "oiio_packages/oiio-2.0.5-cp37-none-macosx_10_13_x86_64.whl", markers = "sys_platform == darwin" },
    { path = "oiio_packages/oiio-2.0.5-cp37-none-linux_x86_64.whl", markers = "sys_platform == linux" },
]

[tool.poetry.dev-dependencies]
black = "^20.8b1"
pytest = "^6.1.2"
mypy = "^0.790"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
