[tool.poetry]
name = "cato"
version = "0.22.1"
description = "coolest project"
authors = ["Jan Honsbrok <jan.honsbrok@gmail.com>"]
include = [
    "cato_server/static/**/*"
]
packages = [
    { include = "cato" },
    { include = "cato_server" },
    { include = "cato_api_client" },
    { include = "cato_api_models" },
]

[tool.poetry.scripts]
cato = 'cato.__main__:main'
cato_server_admin = 'cato_server.cato_server_admin:main'

[tool.poetry.dependencies]
python = "^3.7"
emoji = "^0.6.0"
pinject = "^0.14.1"
jsonschema = "^3.2.0"
contexttimer = "^0.3.3"
humanfriendly = "^8.2"
tabulate = "^0.8.7"
Jinja2 = "^2.11.2"
attrs = "^20.3.0"
alembic = "^1.4.3"
SQLAlchemy = "^1.3.20"
psycopg2 = "^2.8.6"
py-cpuinfo = "^7.0.0"
psutil = "^5.7.3"
Flask = "^1.1.2"
gevent = "^20.9.0"
GitPython = "^3.1.11"
marshmallow = "^3.9.1"
requests = "^2.25.0"
marshmallow-enum = "^1.5.1"
python-dateutil = "^2.8.1"
pathvalidate = "^2.3.1"
conjure-python-client = "^1.10.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
pytest = "^6.1.2"
mypy = "^0.790"
bumpversion = "^0.6.0"
coverage = "^5.3"
random-open-port = "^0.0.3"
flake8 = "^3.8.4"
flake8-print = "^4.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
