from typing import Any

class Annotation:
    def __init__(self, annotation_obj: Any) -> None: ...
    def as_adjective(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
    def __hash__(self) -> Any: ...

class _NoAnnotation:
    def as_adjective(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
    def __hash__(self) -> Any: ...

NO_ANNOTATION: Any
