from . import annotations as annotations
from typing import Any, Optional

class BindingKey:
    def __init__(self, name: Any, annotation: Any) -> None: ...
    def annotation_as_adjective(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
    def __hash__(self) -> Any: ...

def new(arg_name: Any, annotated_with: Optional[Any] = ...): ...
