from . import arg_binding_keys as arg_binding_keys, decorators as decorators, errors as errors, support as support
from typing import Any

class ObjectProvider:
    def __init__(self, binding_mapping: Any, bindable_scopes: Any, allow_injecting_none: Any) -> None: ...
    def provide_from_arg_binding_key(self, injection_site_fn: Any, arg_binding_key: Any, injection_context: Any): ...
    def provide_class(self, cls: Any, injection_context: Any, direct_init_pargs: Any, direct_init_kwargs: Any): ...
    def call_with_injection(self, provider_fn: Any, injection_context: Any, direct_pargs: Any, direct_kwargs: Any): ...
    def get_injection_pargs_kwargs(self, fn: Any, injection_context: Any, direct_pargs: Any, direct_kwargs: Any): ...
