from . import binding_keys as binding_keys, locations as locations
from typing import Any, Optional

class RequiredBinding:
    binding_key: Any = ...
    require_loc: Any = ...
    def __init__(self, binding_key: Any, require_loc: Any) -> None: ...

class RequiredBindings:
    def __init__(self) -> None: ...
    def require(self, arg_name: Any, annotated_with: Optional[Any] = ...) -> None: ...
    def get(self): ...
