from . import errors as errors
from typing import Any

def items(dict_instance: Any): ...
def is_sequence(arg_value: Any): ...
def is_string(arg_value: Any): ...
def is_constructor_defined(cls): ...
def get_method_args(fn: Any): ...
def verify_callable(fn: Any, arg_name: Any) -> None: ...
def verify_subclasses(seq: Any, required_superclass: Any, arg_name: Any) -> None: ...
def verify_module_types(modules: Any, arg_name: Any) -> None: ...
def verify_class_types(seq: Any, arg_name: Any) -> None: ...
def verify_class_type(elt: Any, arg_name: Any) -> None: ...
