name: CI

on: [push]

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: install apt packages
      run: |
        sudo apt-get update
        sudo apt-get install postgresql-12 postgresql-client-12
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build --info
    - name: Lint with Gradle
      run: ./gradlew lint --info

  build_macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python: [ 3.7 ]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --info
      - name: Lint with Gradle
        run: ./gradlew lint --info

  build_windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python: [ 3.7 ]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Build with Gradle
        run: .\gradlew build --info
      - name: Lint with Gradle
        run: .\gradlew lint --info