name: CI

on: [push]

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: install apt packages
      run: |
        sudo apt-get update
        sudo apt-get install postgresql-12 postgresql-client-12 openimageio-tools
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build --info
    - name: Lint with Gradle
      run: ./gradlew lint --info
    - uses: actions/upload-artifact@v2
      with:
        name: wheel-linux
        path: |
          ./dist/*.whl

  build_windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python: [ 3.7 ]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Setup OpenImageIO
        run: |
          curl --location https://github.com/Latios96/oiio-building/releases/download/v2.2.7.0-test/openimageio-2.2.7.0-windows.tar --output openimageio-2.2.7.0-windows.tar
          tar -xvf openimageio-2.2.7.0-windows.tar
          echo "$env:GITHUB_WORKSPACE\build\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Build with Gradle
        run: .\gradlew build --info
      - name: Lint with Gradle
        run: .\gradlew lint --info
