name: Update Dependencies

on:
  schedule:
    - cron: '0 6 * * 1,6'

jobs:
  update_dependencies:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Update Yarn Dependencies
        run: ./gradlew :frontend:yarnUpgrade
      - name: Update Poetry Dependencies
        run: ./gradlew poetryUpdate

      - name: Disable Git Hooks
        run: rm -rf .git/hooks

      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: update/update-dependencies
          title: Update dependencies
          body:  Update dependencies
          commit-message: "chore(deps): Update dependencies"
          delete-branch: true